### ISSUE TITLE
Грусть

### ISSUE THREAD

**Issue by zeminor** [russian-plan/first#7]
Похоже на инициативу положили х*й!

**Comment by horosgrisa** [comment]
А почему бы не сделать самому несколько предложений и предложить pull-request?

**Comment by kisik21** [comment]
@horosgrisa ну надо же во всем всех обвинить!

**Comment by horosgrisa** [comment]
@kisik21 А вообще есть какие-то предложения?

**Comment by alsii** [comment]
Ну там же написано: в мае. У вас май закончился? У меня нет. Значит сидим и ждем. Вот не дождемся если, тогда можно и самим что-нибудь замутить :) Непротивозаконное ;) Так что, дорогие авторы проекта, у вас срок - 1 июня, День защиты детей :)

**Comment by alsii** [comment]
Кстати, интересно, что репозиторий называется First, что как бы намекает, что план может оказаться не последним ;) Хотя может это означает "первый этап"? ;)

**Comment by russian-plan** [comment]
Раздел "Issues" временно закрыт, так как тем, кто подписался начало приходить слишком много писем со спамом. Официальная почтовая рассылка доступна по ссылке на главной странице репозитария.

**Comment by valmat** [comment]
Гугл групп тогда откройте. Интересно же было.

13 мая 2015 г., 17:49 пользователь russian-plan <notifications@github.com>
написал:

**Comment by kisik21** [comment]
Чего не знаю, того не знаю.

С уважением, ヴ｡
Отправлено с моего Windows Phone
________________________________

**Comment by alexey26** [comment]
Печаль
14 мая 2015 г. 7:27 пользователь "kisik21" <notifications@github.com>
написал:
